### ISSUE TITLE
Community Action

### ISSUE THREAD

**Issue by kpheasey** [fast-jsonapi/fast_jsonapi#1]
We are starting an official/unofficial fork Netflix/fast_jsonapi.  Until that project's maintainer is active, we will keep development going.

There are a few things we need to handle to make this successful.

- [x] Migrate PR's from official repo.
  - It would be best to credit the original authors.  Maybe we can contact everyone and give them 30 days to respond.  Otherwise we will copy and give credit in some documentation?
  - Consider [_unforking_](https://github.com/fast-jsonapi/fast_jsonapi/issues/24)...
- [x] Determine how to handle gem releases
  - Putting a second gem on rubygems is not ideal.  Unless someone needs the gem, using github releases might be sufficient.
- [x] Setup PR review process
  - Status Checks
    - TravisCI
    - Codeclimate/Rubocop (not required)
    - Coveralls (ensure test coverage does not drop)
  - Maintainer assigns themselves and does a code review before merge
  - Squash PR (it's nice to cut down on noisy commits to pass status checks)
- [x] Get 3 maintainers
  1. @jopotts 
  2. @kpheasey 
  3. @stas

**Comment by jopotts** [comment]
Thanks @kpheasey ! All good points above. 👍 

To get the ball rolling, I've added the PR I had on the original repo which was easier than I'd thought.

To add https://github.com/Netflix/fast_jsonapi/pull/411 for example, you can simply create a new PR direct from a URL like this: https://github.com/fast-jsonapi/fast_jsonapi/compare/dev...krzysiek1507:maintenance/test-against-ruby-2-6 (cut & paste title and description)

ie. Paste the source branch after the 3 dots:
`https://github.com/fast-jsonapi/fast_jsonapi/compare/dev...krzysiek1507:maintenance/test-against-ruby-2-6`

I think it would be best to ask the original authors to do that. @krzysiek1507

For the release of gems, we should use the github release for now, with the purpose of this fork being to get PRs merged and things moving again, and then hopefully the guys at Netflix can either merge back or at least add other maintainers. Also it would be good to get more maintainers on this repo so it's more of a community effort.

**Comment by krzysiek1507** [comment]
Created #3. I hope it still works! ;)

**Comment by krzysiek1507** [comment]
Please let me know if you want my other PR to be created for this repo. https://github.com/Netflix/fast_jsonapi/pulls/krzysiek1507

**Comment by kpheasey** [comment]
@krzysiek1507 Thanks for #3!  Your other PR's look great too, please pull them over.  Any interest in being a maintainer?

**Comment by krzysiek1507** [comment]
@kpheasey unfortunately, I don't have enough time for being a maintainer currently.

**Comment by kpheasey** [comment]
No worries, thanks for your contributions!

**Comment by krzysiek1507** [comment]
I've just created a few more PRs with fixes that I made a long time ago.

**Comment by kpheasey** [comment]
I merged in some of the PR's and await feedback on others.  Additionally, master was behind dev, so I rebased it.

Don't know when I can setup all the status checks, but Travis is good for now.

**Comment by stas** [comment]
@kpheasey I'm very interested to be part of the reviews. Mainly, because of the https://github.com/stas/jsonapi.rb

I already subscribed to the notifications and will try to jump in when possible.

>  Determine how to handle gem releases
> 
> * Putting a second gem on rubygems is not ideal.  Unless someone needs the gem, using github releases might be sufficient.

Since there are projects depending on the original gem, it won't be easy to manage the dependencies outside the rubygems. There are 4 people listed as maintainers on Rubygems, can we email them and ask for a proper update please? Alternatively just go for the `faster_jsonapi` :trollface: :see_no_evil:

**Comment by kpheasey** [comment]
@stas Welcome aboard!

I have a similar project to yours that we use internally.  Documentation is still a work in progress, it's a low priority because my team knows it inside out.  https://github.com/kp-software/jsonapi_actions

**Comment by kpheasey** [comment]
@jopotts @stas 

I added a [CHANGELOG](https://github.com/fast-jsonapi/fast_jsonapi/blob/dev/CHANGELOG.md)

Also, I think we should switch to semantic versioning.  Our first release should be 1.6.0, in a week or two once we have active PRs reviewed/merged.

**Comment by kpheasey** [comment]
@jopotts @stas I've merged in another PR that adds conditional links.  There's definitely enough new improvements and additions to warrant the 1.6.0 release at the end of the month!

At that point, we should also open another issue on the main repository, to point people over here.... and maybe catch the dev's attention if we're lucky.

**Comment by stas** [comment]
@kpheasey sounds good, thank you!

Re, the original project, I wouldn't mind setting up an email with those folks who are listed in the gemspec file and ask them directly...

**Comment by kpheasey** [comment]
Contacting them via email sounds like a good approach.  It would be great to get the updates on rubygems.

**Comment by jopotts** [comment]
A release would be great. Definitely warranted. And trying to get the original repo owners' attention is worth a shot too. Ultimately, if the Netflix version becomes active again and they get community support (you guys) then that would be the best outcome in my opinion. Then everyone can continue with updates on the same gem, making everyone's life easier. Thanks for all the hard work on this!

**Comment by stas** [comment]
> Contacting them via email sounds like a good approach. It would be great to get the updates on rubygems.

:zap: :email: :dash:

**Comment by isfalcantara** [comment]
Any updates on contacting the maintainers of the base repo?

**Comment by kpheasey** [comment]
Yes, @stas reached out to the maintainers listed on rubygems.  We received a response from an engineering manager at Netflix on 2019-11-19

```
Hi Stas,

Thanks for reaching out. I have read your email and will get back to you after talking to my teammates.

Thanks
Shishir
```

**Comment by isfalcantara** [comment]
Ok, thanks for the update! :+1:

**Comment by codyeatworld** [comment]
@kpheasey Has there been any update since 2019-11-19 on this?

**Comment by kpheasey** [comment]
@codyeatworld Sorry for the late reply.  We did hear back and they asked for out plans with the project.  Since we relayed our intentions, we haven't heard back :(

**Comment by kpheasey** [comment]
@stas @jopotts I noticed the CHANGELOG has not beed updated with the PR's being merged and closed.  However, it looks like we have had a few changes and may be ready for a release.  If you feel the same, I'll update the CHANGELOG and update the version.

Also, we should ping Netflix again.... Or create a new rubygems listing.  If they are going to take weeks/months to get back to us.  Then we just need to move forward w/o them.  If they never update the original fast_jsonapi then we need to add fast-jsonapi sadly.

**Comment by stas** [comment]
@kpheasey apologies for that, I will look into the latest changes and update it :see_no_evil: 

> Also, we should ping Netflix again.... Or create a new rubygems listing. If they are going to take weeks/months to get back to us, then we just need to move forward w/o them. We should replace the rubygems fast_jsonapi listing with fast-jsonapi.

I don't think we will hear again from Netflix. I also don't find it a good idea to maintain this uncertainty. We can either use github gems hosting and maintain the same name, or rename it to something like `fast_jsonapi.rb` and publish it without any code-related name changes. If the folks from Netflix find time, we'll be more than happy to pick up the conversation though :heart:

**Comment by stas** [comment]
Closing as of ab9db291d4d89ed93029f0844461498364d3be3b

Thanks everyone! :bow:
