### ISSUE TITLE
Relationship scope

### ISSUE THREAD

**Issue by kapso** [fast-jsonapi/fast_jsonapi#19]
Is there a way to add scope to relationship, so something like this 

Serializer:
```ruby
class CompanySerializer
  include FastJsonapi::ObjectSerializer

  has_many :employees_temp, scope: ->(record) { record.employees.temp }, serializer: EmployeeSerializer
  has_many :employees_full_time, scope: ->(record) { record.employees.full_time }, serializer: EmployeeSerializer
end
```

Given the following models:
```ruby
class Company < ApplicationRecord
  has_many :employees
end

class Employee < ApplicationRecord
  scope :temp, -> { where(type: 'temp') }
  scope :full_time, -> { where(type: 'full_time') }
end
```

**Comment by stas** [comment]
@kapso you can use the `object_method_name` parameter to specify any method that wraps or returns a relationship. The serializer will try to build your relationships out of anything that's returned by that mehtod.

**Comment by kapso** [comment]
Thanks. Can you pass a block? So something like... `object_method_name: -> { employees.temp }`

**Comment by stas** [comment]
@kapso nope[1] :slightly_frowning_face: 

[1]: https://github.com/fast-jsonapi/fast_jsonapi/blob/master/lib/fast_jsonapi/relationship.rb#L51

**Comment by bradrobertson** [comment]
@kapso scoping your association shouldn't be the responsibility of a serializer, that's the ORMs duty (to choose which records to load) You can put that in your model though:
```
class Company < ApplicationRecord
  has_many :employees
  has_many : employees_temp, -> { temp }
end
```

**Comment by stas** [comment]
@kapso I'm closing this. There are a couple of ways you can achieve what you were asking for. If there's a specific API design change, please open an issue we can review the suggestion exclusively.
