### ISSUE TITLE
Send :included data inside :relationships.

### ISSUE THREAD

**Issue by AAlvarez90** [fast-jsonapi/fast_jsonapi#22]
Current Issue:
I have noticed that when you include an association for a record. The key :relationships only sends `:id and :type` for that relationship. Then as a sibling of `data` it sends the `included` key with an array of objects which can be differentiated by their `type` attribute.

Additional Information:
https://stackoverflow.com/questions/55782066/how-to-get-the-fast-jsonapi-to-return-the-attributes-of-the-relationships 
https://i.stack.imgur.com/RkF8k.png 

Proposed Solution:
I think it would be way cleaner and consistent to send an `attributes` property with the extra properties that the serialization would provide inside the `relationships` key instead of sending the relationships in a separate property `included`.

So Instead of sending something like:
```json
{
   "data": {
       "id": 1,
       "type": "user",
       "attributes": {
         "email": "sample@email.com",
       },
       "relationships": {
           "organization": {
               "data": {
                 "id": 10,
                 "type": "organization"
               }
           }
       }
   },
   "included": [
       {
          "id": 10, 
          "type":"organization",
          "attributes": {"id":10,"name":"Sample Org"},"relationships":{}
       }
    ]
}
```

We would send this:
```json
{
   "data": {
       "id": 1,
       "type": "user",
       "attributes": {
         "email": "sample@email.com",
       },
       "relationships": {
           "organization": {
               "data": {
                 "id": 10,
                 "type": "organization",
                  "attributes": {"id":10,"name":"Sample Org"},"relationships":{}
               }
           }
       }
   }
}
```

If by any chance the organization was an array, (Or any other association) then:
```json
{
   "data": {
       "id": 1,
       "type": "user",
       "attributes": {
         "email": "sample@email.com",
       },
       "relationships": {
           "organizations": [
              {
                 "data": {
                    "id": 10,
                    "type": "organization",
                    "attributes": {"id":10,"name":"Sample Org"},"relationships":{}
                  }
               },
               {
                  "data": {
                    "id": 11,
                     "type": "organization",
                     "attributes": {"id":11,"name":"Sample Org 2"},"relationships":{}
                  }
                }
             ]
           }
       }
   }
}
```

Thoughts, comments?

**Comment by ujh** [comment]
My guess is that it's done the way it's done because that's how the json:api spec specifies it.

**Comment by stas** [comment]
@AAlvarez90 please [consult the specifications](https://jsonapi.org/format/#document-resource-object-linkage) for this exact question.

Generally speaking, your suggestion would lead to a bunch of complexity (consider circular dependencies and just the size of the payload growing every time your relationship resource is used more than one time). I strongly advise you to start with the documentation I linked above, and even consider asking the folks behind https://github.com/json-api before you adopt such a convention.

Unfortunately, we can not consider this a valid issue for the project.

**Comment by Faisal-nfl** [comment]
@AAlvarez90 
I have to do something like this in UserSerialzier to make desired response.

attribute :organizations do |object|
   OrganizationSerializer.new(object.organizations)
end

not sure if there is any other way.

**IT DOES NOT MAKE SENSE OF FASTER IF APP SIDE HAS PROCESS DATA AS WELL.**

**Comment by stas** [comment]
@Faisal-nfl please address your concerns to the `json-api` fellows. This is just the wrong place to discuss the specs.
