### ISSUE TITLE
Relation attributes are not being serialized in this gem

### ISSUE THREAD

**Issue by Victorcorcos** [fast-jsonapi/fast_jsonapi#241]
## The Issue

I noticed that the item relation attributes are not being serialized in this `gem`, just the `:id` and `:type` keys are being serialized for the relations. Take in mind that I'm talking about the item's relation(s), not about the item itself that is being serialized.

How can we serialize the attributes of the item relations in this gem?
Is there an option for that already?

* Setup:

```rb
# .../app/serializers/attachment_serializer.rb
class AttachmentSerializer
  include JSONAPI::Serializer

  attributes :id, :name

  belongs_to :project
end
```

```rb
# .../app/serializers/project_serializer.rb
class ProjectSerializer
  include JSONAPI::Serializer

  attributes :id, :name, :active

  has_many :users
end
```

* How to Reproduce

```rb
attachment = Attachment.last
AttachmentSerializer.new(attachment).serializable_hash
```

⚠️ this is not displaying either project's `name` and `active` attributes after the serialization.

## Expected Behavior

```rb
{:id=>"637cf4d769ca9c09a5f6a0d8",
 :type=>:attachment,
 :attributes=>
  {:id=>BSON::ObjectId('637cf4d769ca9c09a5f6a0d8'),
   :name=>"PostMan Tutorial",},
 :relationships=>
  {:project=>{:data=>{:id=>BSON::ObjectId('641d2f6c69ca9c0f54edfb10'),
                      :name=>"Project with Sheet View",
                      :active=>true}}
```

## Actual Behavior

```rb
{:id=>"637cf4d769ca9c09a5f6a0d8",
 :type=>:attachment,
 :attributes=>
  {:id=>BSON::ObjectId('637cf4d769ca9c09a5f6a0d8'),
   :name=>"PostMan Tutorial",},
 :relationships=>
  {:project=>{:data=>{:id=>"62ed6a75a6af03010ff96521"}}
```

## Specifications

  - Version: 2.2.0
  - Ruby version: 3.2.2

**Comment by stas** [comment]
@Victorcorcos please review the JSONAPI spec re the includes:
https://jsonapi.org/format/#fetching-includes

The implementation is following the spec document.

**Comment by batter** [comment]
I understand this may be following the spec, however, what is the need to specify a serializer for an associated object if it's not going to use the serializer for the associated object to serialize out the nested attributes? The only thing it seems to do when you have an associated object for attributes is print out the `id` and `type` (type generally just being the name of the class). That could easily be done without a serializer right?

I would think it would be much more useful to at least provide the option to serializer the nested attributes of the associated object(s)?

**Comment by stas** [comment]
> I would think it would be much more useful to at least provide the option to serializer the nested attributes of the associated object(s)?

@batter tbh I'm not involved in the drafting of the spec, I think these questions are more relevant in the context of https://github.com/json-api/json-api

To answer specifically ...

> what is the need to specify a serializer for an associated object if it's not going to use the serializer for the associated object to serialize out the nested attributes

The serializer handles the `id` serialization (it could be a non-standard attribute) and the `type`, which could be non-standard value and not inherit the name of the serializer class at all. So to me, it makes sense to be explicit in what serializer was specified for relationship(s).

It also simplifies the api of the library, you don't have to define a serializer for relationships only, but also for the `includes`. Wherever one decides to use the later, it's optionally "ready". (In #141 I went further and removed things like `id_method_name` to keep _a single source of truth_)

---

On a personal note, I think nesting data in RESTful APIs is a nightmare to deal with, and seeing folks sending payloads that upsert a whole collection of a record via the record endpoint is the right path to a lot of headaches. So to me, these limitations are enforcing a separation of concerns and healthier architecture, but I'm sure everyone has their opinion on this :smiley:

**Comment by Victorcorcos** [comment]
@stas Thanks for the answer, although it didn't work here. I believe it didn't work because the relationship in my scenario is not designed via `has_one` / `has_many` / `belongs_to`, but via [`embeds_one`](https://www.mongodb.com/docs/mongoid/6.4/tutorials/mongoid-relations/#embeds-one), which is a relationship derived from `mongoid` gem, which is an object-document mapper (ODM) for the Mongo Database.

Well, I created a different way to handle the `embeds_one` relationship in my serialized object by assigning a block to the correspondent relationship attribute:

* Class
```rb
class Project < ApplicationRecord
  embeds_one :project_setting, autobuild: true
end
```

* Serializer
```rb
class ProjectSerializer
  include JSONAPI::Serializer

  attribute :project_setting do |item|
    ProjectSettingSerializer.new(item.project_setting).serializable_hash[:data][:attributes]
  end
end
```

Do you see a performance issue with that solution?

**Comment by stas** [comment]
> Do you see a performance issue with that solution?

Hey, I'm not familiar with what works best for mongoid, but you can always enable caching so that should at least reduce the hits on the database.

Feel free to close the issue if you have a workaround :bow:

**Comment by Victorcorcos** [comment]
@stas, I noticed you mentioned about enable caching, but it never worked here because of a `SystemStackError` error.

[I opened this **Issue,** so we can discuss about that here](https://github.com/jsonapi-serializer/jsonapi-serializer/issues/242)

```rb
irb(main):001:0> record = Record.last
=> #<Record _id: 64d6c2f669ca9c141907bc07, created_at: 2023-08-11 23:23:34.424 UTC, updated_at: 2023-08-11 23:23:34.424 UTC, created_by_id: nil, updated_by_id: nil, project_id: BSON::Obje...
irb(main):002:0> RecordSerializer.new(record).serializable_hash
irb(main):002:0> RecordSerializer.new(record).serializable_hash
/Users/victorcosta/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/cache.rb:770:in `expanded_version': stack level too deep (SystemStackError)
```

It happens after I enable cache on the serializer(s) via

```rb
  cache_options store: Rails.cache, namespace: "jsonapi_serializer", expires_in: 1.hour
```

For example

```rb
class RecordSerializer
  include JSONAPI::Serializer

  attributes :id do |item|
    item.id&.to_s
  end

  cache_options store: Rails.cache, namespace: "jsonapi_#{name.underscore}", expires_in: 1.hour
end
```

Do you happen to know why this `SystemStackError` is happening? It is being impossible to enable cache right here while using this gem because of that issue. </3

Thanks!
