### ISSUE TITLE
group_by not working

### ISSUE THREAD

**Issue by wadahkode** [fast-jsonapi/fast_jsonapi#244]
I have a problem when using Model.all.group_by { |t| t.category  }

I want to get the final result from data like this :

`
[{
   products: [
      "hardware" : [{}, {}],
      "software"  : [{}, {}]
   ]
}]
`

But I have a problem, namely: 

`"#<FastJsonapi::MandatoryField: id is a mandatory field in the jsonapi spec>"`

I need the key of the category to be displayed on the front end, can anyone help?

I want the front-end not to work to process this.

**Comment by stas** [comment]
@wadahkode this is not related to this library, please review the data you're passing to the serializers, the error is pretty self-explanatory.

I'm going to close the issue, but feel free to keep the conversation open.

**Comment by wadahkode** [comment]
Oke, thanks
