### ISSUE TITLE
Allow a relationship's serializer to be computed based on the object

### ISSUE THREAD

**Issue by christophersansone** [fast-jsonapi/fast_jsonapi#29]
Thanks so much for picking up the ball with this project!  I was an early contributor.

When a relationship is defined, the serializer needs to determine which serializer to use.  It uses both the optional `serializer` and `polymorphic` options to help guide it.  It gets the job done in most cases, but there are definitely some hard rules that don't necessarily apply in all cases.

Consider the case of Single Table Inheritance.  Say you have an `Animal` base class and 20 subclasses, `Dog`, `Pig`, `Giraffe`, etc.  You may have different serialization rules for each, so they should each have their own serializer.  Or maybe they all have the same serializer.  Or maybe they have the same base class serializer, and only the ones that have something custom would need to define their own serializer.  Maybe this can be done today using a `polymorphic` hash, but (a) you would have to list every possible class in the hash, and (b) it looks like there are some similar rules and limitations with how `record_type` is defined with polymorphic hashes.

I think an elegant solution would be to simply allow the `serializer` option to be specified as a `Proc`, like we do with attributes, conditionals, etc.  It can include the same `object` and `params` arguments.  This way, the author has total control over selecting the serializer based on the actual object that it is attempting to serialize.

What do you think of this approach?  If it looks good, I will implement and create a PR.

Thanks again!

**Comment by stas** [comment]
@christophersansone I appreciate the openness here to help!

Would you be kind to share some sort of a higher spec/API you're suggesting here please. I don't want us to write user stories, but having a list of use-cases and how exactly the API will look/change would be a great starting point.

My main concern here is that something like this, could lead to some breaking changes, so some prior discussion could help other folks share their concerns at least.

In my projects we don't really deal with polymorphic things, but I do agree that the whole relationships API is pretty messy and have a cleaner refactoring will make everyone so much happy.

**Comment by christophersansone** [comment]
Thanks for the quick reply, @stas !  The PR will arrive shortly.

This is the general idea for the API and an example:

```ruby
  class ZooSerializer
    include FastJsonapi::ObjectSerializer

    has_many :animals, serializer: -> (object) do
      if object.is_a?(Mammal)
        MammalSerializer
      elsif object.is_a(Bird)
        BirdSerializer
      end
    end
  end
```

Some use cases:

1. The API has a much clearer intent than the `polymorphic` hash.  The polymorphic hash values are symbols, so it is unclear if those are supposed to be the record types or the serializer lookup.  The current implementation can lead to problems like #30, which to me is a result of the lack of clarity in the API.

2. It has more flexibility than `polymorphic`.  If I have 20 different polymorphic classes, and they can all use a default serializer except for two of the classes, I can't simply write the Ruby logic to select the serializer today.  Instead I have to write all 20 possible classes, and if I ever add another class, I need to remember to update all of these relationships, even if it should just use the default serializer.

3. It works for Single Table Inheritance.  ActiveRecord considers STI and polymorphism to be different.  The concepts are similar in that a relationship may have different classes, but with STI you know they are all of a base type and share many of the same properties.  In ActiveRecord, `polymorphic: true` is specifically for polymorphism and not STI.  Today, this library can support the notion of STI through the `polymorphic` functionality, but it feels like it just happens to work rather than it being intentionally supported, and you run into the problems with `polymorphic` that I describe above.

4. Ultimately, we give total control to the developer to decide which serializer to use.  Often it will be based on the object's class, but not always.  There may be a specific property of an object that you may want to invoke a different serializer for.  Or maybe you have a table with 200 fields and sometimes want to opt in to using a sparse serializer for certain relationships at certain times.  I'm not sure how everyone will wind up using it, but I love that this is a simple and consistent API that lets developers select a serializer based on whatever requirement they have.  If you can execute Ruby code and be given the object and the parameters to serializer, what more could you ask for?

Hope this helps clear things up.  Let me know what you think!

**Comment by allomov** [comment]
Hello, @christophersansone. I am more interested in case, when Serializer can determine what serializer should be used for particular object. I think this may work both for STI and polymorphic dependencies.

Here is a code to demonstrate the idea:
```
# STI
class Vehicle < AR
end
class Car < Vehicle
end
class Airplane < Vehicle
end

# Polymorphic relation
class Cargo < AR
  belongs_to :delivered_by, polymorphic: true
end

# Serializers
class VehicleSerializer
  polymorphic_types Car => CarSerializer, Airplane => AirplaneSerializer
end

class CargoSerializer
  has_one :delivered_by, serializer: VehicleSerializer
end
```
What do you think about it?

**Comment by christophersansone** [comment]
@allomov Thanks for your input!  So first of all, I think this can be accomplished today:

```ruby
class CargoSerializer
  has_one :delivered_by, polymorphic: true
end

class CarSerializer
  ...
end

class AirplaneSerializer
  ...
end
```

This is pretty much the use case of `polymorphic: true`, when you can infer the serializer name from the object class.

If the serializer name cannot be inferred, you can define `polymorphic` as a hash, similar to your `polymorphic_types`:

```ruby
class CargoSerializer
  has_one :delivered_by, polymorphic: { Car => :car, Airplane => :airplane }
end
```

This issue and PR offers a more generic approach that allows the developer to build their own logic for determining a serializer, whether it is polymorphic, STI, or any other custom requirement:

```ruby
class CargoSerializer
  has_one :delivered_by, serializer: Proc.new do |object|
    if object.is_a?(Car)
      CarSerializer
    elsif object.is_a(Airplane)
      AirplaneSerializer
    else
      VehicleSerializer
    end
  end
end
```

With this new approach, you can also do something like this, where you can define the serializer proc once and use it on multiple relationships:

```ruby
class VehicleSerializer
    def self.vehicle_serializer_proc
      @vehicle_serializer_proc ||= Proc.new |object|
        if object.is_a?(Car)
          CarSerializer
        elsif object.is_a?(Airplane)
          AirplaneSerializer
        else
          VehicleSerializer
        end
      end
    end
end

class CargoSerializer
  has_one :delivered_by, serializer: VehicleSerializer.vehicle_serializer_proc
end

class AnotherSerializer
  has_one :delivered_by, serializer: VehicleSerializer.vehicle_serializer_proc
end
```

This last approach is pretty similar to your example, where you are defining the serializer selection on the base STI class.  I am using this PR myself in production and have implemented something similar myself.  I like the amount of flexibility it offers: it can be used many different ways, and the serializer can be selected based on criteria other than object type.

**Comment by allomov** [comment]
Thank you very much for your answer. Will try it out today.
