### ISSUE TITLE
Dynamically assigning `set_type`

### ISSUE THREAD

**Issue by benwalsh** [fast-jsonapi/fast_jsonapi#31]
Something similar to this was raised [in the previous incarnation](https://github.com/Netflix/fast_jsonapi/issues/126). In my case, I have two different associations of the same record type. I want to serialize them both using the same serializer.

For context, this is an app where one association is a (relatively) static one derived from the object's ActiveRecord associations, and the other is a dynamic list of search results based on user input. So it doesn't really make sense to combine them all in one association and then pull them apart.

It seems I can't pass in `set_type` from outside, I can only specify it in the serializer itself, and then it's immutable. But this is what I _want_ to do:

```
class  OrderSerializer
  include FastJsonapi::ObjectSerializer

  has_many :eligible_accounts, serializer: AccountSerializer, set_type: :eligible_account do |order|
    order.accounts.eligible
  end

  has_many :search_results, serializer: AccountSerializer, set_type: :search_result do |_order, params|
    params[:search_results]
  end
end
``` 

```
class AccountSerializer
  include FastJsonapi::ObjectSerializer

  attributes :name, :code, :status 
end
```

Does this make sense?

**Comment by christophersansone** [comment]
@benwalsh I'm doing similar work with dynamically assigning a serializer (see #29).  I was actually thinking about this exact thing and wasn't sure if it was ever necessary.  Good to know at least one person needs it!

The good news is that I think your use case is supported today by simply defining different serializers, e.g.

```ruby
class AccountSerializer
  # all your serializer logic
end

class EligibleAccountSerializer < AccountSerializer
  set_type :eligible_account
end

class SearchResultSerializer < AccountSerializer
  set_type :search_result
end
```

Does this solve the problem for you?

**Comment by benwalsh** [comment]
That works nicely, thanks -- of course it would be great not to have to have multiple files doing the same thing, but this does the trick.

**Comment by phlegx** [comment]
Hi! I can solve my issue like described by @christophersansone, thanks for that.

**BUT**, be able to set `set_type` to a relationship can help to reduce a lot of code. Instead of declare multiple serializer classes that inherits from one serializer and sets different types like @christophersansone shows, all this relationships can be serialized simply with:

```ruby
class  OrderSerializer
  include FastJsonapi::ObjectSerializer

  has_many :first_results, serializer: AccountSerializer, set_type: :first_result
  has_many :second_results, serializer: AccountSerializer, set_type: :second_result
  has_many :last_results, serializer: AccountSerializer, set_type: :last_result
end
```

Could this be a useful feature?
