### ISSUE TITLE
Tips and Tricks

### ISSUE THREAD

**Issue by christophersansone** [fast-jsonapi/fast_jsonapi#38]
In spending time reviewing issues and PRs lately, I have seen several questions and concerns that can be solved easily in userland.  It's awesome that the library is flexible enough to support these needs, but it may not be obvious.  Some things that come to mind:

* How do I initiate the serialization from my controller?
* How can I reuse a commonly used block or Proc?
* Recommendations for hash-to-JSON serialization (#12)
* How can I serialize differently when a record is in `data` vs. `included`? (#37)

I think it would help to offer these things in a "Tips and Tricks" / "Cookbook" / "Best Practices" area.  This can either be directly in the README, in a separate Markdown file, or the Wiki.  Using the wiki or not mostly would depend on whether the maintainers want to control updates via the PR process or not.

I also think that this would help the maintainers understand how the community is solving common problems and use the list to determine how to better improve the experience.

I can start it once we reach a decision about where it should go.

**Comment by stas** [comment]
@christophersansone I was looking into this recently and I think we're better off having a `docs` folder where we throw all the documentation. I can set up the `yardoc` to build the static documentation and even deploy it to a github pages repo. Would you be onboard with that?
