### ISSUE TITLE
Type in included relationship is singular

### ISSUE THREAD

**Issue by BFranse** [fast-jsonapi/fast_jsonapi#55]
Fair warning: I'm new to JSON, API and JSON:API formatting but I ran into an issue which I described in detail on [Stackoverflow](https://stackoverflow.com/questions/59962160/parsehasmany-model-type-for-relationship-x-not-found-how-do-i-map-nested-j). I _think_ I have found what the issue is, but I am not 100% sure it is an issue with this project, or an issue with my code. 

According to the documentation on [JSON:API](https://jsonapi.org/) and the example given on that page, the value of 'type' in the include part and the relationship data of the response is returned as plural: 'people' and 'comments'.
However when I return a response with included relationships the type is returned as singular:
(One role has many accountabilities and one accountability belongs to a role in my project)
```json
{
    "data": [
        {
            "id": "1",
            "type": "role",
            "attributes": {
                "name": "Farming Engineer",
                "purpose": "Iure voluptatum rem dolores.",
                "created_at": "2020-01-16T18:38:26.151Z",
                "updated_at": "2020-01-16T18:38:26.151Z"
            },
            "relationships": {
                "accountabilities": {
                    "data": [
                        {
                            "id": "6",
                            "type": "accountability"
                        },
                        {
                            "id": "12",
                            "type": "accountability"
                        }
                    ]
                }
            }
        },
        {
            "id": "2",
            "type": "role",
            "attributes": {
                "name": "IT Supervisor",
                "purpose": "Iusto fuga fugiat qui.",
                "created_at": "2020-01-16T18:38:26.161Z",
                "updated_at": "2020-01-16T18:38:26.161Z"
            },
            "relationships": {
                "accountabilities": {
                    "data": []
                }
            }
        }
    ],
    "included": [
        {
            "id": "6",
            "type": "accountability",
            "attributes": {
                "description": "penetrate the market",
                "created_at": "2020-01-16T18:38:26.480Z",
                "updated_at": "2020-01-16T18:38:26.480Z"
            },
            "relationships": {
                "role": {
                    "data": {
                        "id": "1",
                        "type": "role"
                    }
                }
            }
        },
        {
            "id": "12",
            "type": "accountability",
            "attributes": {
                "description": "immersive experience",
                "created_at": "2020-01-16T18:38:26.507Z",
                "updated_at": "2020-01-16T18:38:26.507Z"
            },
            "relationships": {
                "role": {
                    "data": {
                        "id": "1",
                        "type": "role"
                    }
                }
            }
        }
    ]
}
```

Am I doing something wrong or am I missing something? Any information is very much appreciated.

**Comment by stas** [comment]
@BFranse the short answer is that the spec is agnostic regarding the `type` value as long as it's consistent and servers correctly the purpose of [identification of the resource](https://jsonapi.org/format/#document-resource-object-identification).

> Note: This spec is agnostic about inflection rules, so the value of type can be either plural or singular. However, the same value should be used consistently throughout an implementation.

So it's up to you if you want to have singular or plural. What exactly are you trying to achieve in fact?

**Comment by BFranse** [comment]
@stas Thank you for clearing that up. What I am trying to achieve is to map my json response to models in Angular. I was running into an issue where the module I am using on my front end gives me an error about not being able to find model type. (That's the TL:DR, there's a more in-depth explanation on the [Stackoverflow](https://stackoverflow.com/questions/59962160/parsehasmany-model-type-for-relationship-x-not-found-how-do-i-map-nested-j) topic I made, if you're interested.)

I then checked the examples on JSON:API and my response and noticed the differences in singular/plural for the value of `type`. As a test I manually changed the JSON response from singular to plural and that seemed to work alright.

At that point I was confused which form I was suppose to use, and I didn't see a clear way to change the value of `type` in the response.  Do you have any pointers as to where I am able to change that? I thought `set_type` would take care of that, but it does not quite produce the result I expected.
Thanks for your patience in this matter and thanks in advance for your help.

**Comment by stas** [comment]
>  Do you have any pointers as to where I am able to change that? I thought `set_type` would take care of that, but it does not quite produce the result I expected.
> Thanks for your patience in this matter and thanks in advance for your help.

@BFranse `set_type` should be the way to do it. Is there a particular issue we could reproduce, maybe you can share some examples/code?

**Comment by BFranse** [comment]
> > Do you have any pointers as to where I am able to change that? I thought `set_type` would take care of that, but it does not quite produce the result I expected.
> > Thanks for your patience in this matter and thanks in advance for your help.
> 
> @BFranse `set_type` should be the way to do it. Is there a particular issue we could reproduce, maybe you can share some examples/code?

I am probably doing something wrong then. In my (simplified) example I have two models. Roles and accountabilities. One role can has many accountabilities, and one accountability belongs to a role.

This is my current code:

**role.rb** (Simplified, without validations, etc.)
```ruby
class Role < ApplicationRecord
  has_many :accountabilities
end
```

**accountability.rb** (Simplified, without validations, etc.)
```ruby
class Accountability < ApplicationRecord
  belongs_to :role
end
```

**role_serializer.rb**
```ruby
class RoleSerializer
  include FastJsonapi::ObjectSerializer

  set_type :role
  has_many :accountabilities

  attributes :name,
             :purpose,
             :created_at,
             :updated_at
end
```

**accountability_serializer.rb**
```ruby
class AccountabilitySerializer
  include FastJsonapi::ObjectSerializer

  set_type :accountability
  belongs_to :role

  attributes :description,
             :created_at,
             :updated_at
end
```

**json_concern.rb**
```ruby
module JsonConcern
  extend ActiveSupport::Concern

  def json_response(data, status)
    render json: data,
           status: status.parameterize.underscore.to_sym
  end
end
```

**roles_controller.rb** (Simplified)
```ruby
module Api
  module V1
    class RolesController < ApiController
      ...
      def index
        roles = (user_id = params[:user_id]) ? Role.by_user(user_id) : Role.all
        json_response(serialize(roles), (roles.any? ? 'ok' : 'not_found'))
      end
      ...
      def serialize(role)
        options = {}
        if params[:include].present?
          options[:include] = params[:include].split(',').map(&:to_sym)
        end
        RoleSerializer.new(role, options)
      end
    end
  end
end
```

When I currently send a GET request with postman to `http://localhost:3000/api/v1/roles?include=accountabilities` this is the response I get. I shortened it to a few records and their associated records:

**Current json response**
```json
{
  "data": [
    {
      "id": "1",
      "type": "role",
      "attributes": {
        "name": "Farming Engineer",
        "purpose": "Iure voluptatum rem dolores.",
        "created_at": "2020-01-16T18:38:26.151Z",
        "updated_at": "2020-01-16T18:38:26.151Z"
      },
      "relationships": {
        "accountabilities": {
          "data": [
            {
              "id": "6",
              "type": "accountability"
            },
            {
              "id": "12",
              "type": "accountability"
            }
          ]
        }
      }
    },
    {
      "id": "2",
      "type": "role",
      "attributes": {
        "name": "IT Supervisor",
        "purpose": "Iusto fuga fugiat qui.",
        "created_at": "2020-01-16T18:38:26.161Z",
        "updated_at": "2020-01-16T18:38:26.161Z"
      },
      "relationships": {
        "accountabilities": {
          "data": []
        }
      }
    },
    {
      "id": "3",
      "type": "role",
      "attributes": {
        "name": "Product Consulting Planner",
        "purpose": "Facilis natus ex tempora.",
        "created_at": "2020-01-16T18:38:26.168Z",
        "updated_at": "2020-01-16T18:38:26.168Z"
      },
      "relationships": {
        "accountabilities": {
          "data": [
            {
              "id": "3",
              "type": "accountability"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "id": "6",
      "type": "accountability",
      "attributes": {
        "description": "penetrate the market",
        "created_at": "2020-01-16T18:38:26.480Z",
        "updated_at": "2020-01-16T18:38:26.480Z"
      },
      "relationships": {
        "role": {
          "data": {
            "id": "1",
            "type": "role"
          }
        }
      }
    },
    {
      "id": "12",
      "type": "accountability",
      "attributes": {
        "description": "immersive experience",
        "created_at": "2020-01-16T18:38:26.507Z",
        "updated_at": "2020-01-16T18:38:26.507Z"
      },
      "relationships": {
        "role": {
          "data": {
            "id": "1",
            "type": "role"
          }
        }
      }
    },
    {
      "id": "3",
      "type": "accountability",
      "attributes": {
        "description": "rubber meets the road",
        "created_at": "2020-01-16T18:38:26.466Z",
        "updated_at": "2020-01-16T18:38:26.466Z"
      },
      "relationships": {
        "role": {
          "data": {
            "id": "3",
            "type": "role"
          }
        }
      }
    }
  ]
}
```

Now if I change the values of `set_type` in the serializers to plural, the response is as follows:

**Changed json response**
```json
{
  "data": [
    {
      "id": "1",
      "type": "roles",
      "attributes": {
        "name": "Farming Engineer",
        "purpose": "Iure voluptatum rem dolores.",
        "created_at": "2020-01-16T18:38:26.151Z",
        "updated_at": "2020-01-16T18:38:26.151Z"
      },
      "relationships": {
        "accountabilities": {
          "data": [
            {
              "id": "6",
              "type": "accountability"
            },
            {
              "id": "12",
              "type": "accountability"
            }
          ]
        }
      }
    },
    {
      "id": "2",
      "type": "roles",
      "attributes": {
        "name": "IT Supervisor",
        "purpose": "Iusto fuga fugiat qui.",
        "created_at": "2020-01-16T18:38:26.161Z",
        "updated_at": "2020-01-16T18:38:26.161Z"
      },
      "relationships": {
        "accountabilities": {
          "data": []
        }
      }
    },
    {
      "id": "3",
      "type": "roles",
      "attributes": {
        "name": "Product Consulting Planner",
        "purpose": "Facilis natus ex tempora.",
        "created_at": "2020-01-16T18:38:26.168Z",
        "updated_at": "2020-01-16T18:38:26.168Z"
      },
      "relationships": {
        "accountabilities": {
          "data": [
            {
              "id": "3",
              "type": "accountability"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "id": "6",
      "type": "accountabilities",
      "attributes": {
        "description": "penetrate the market",
        "created_at": "2020-01-16T18:38:26.480Z",
        "updated_at": "2020-01-16T18:38:26.480Z"
      },
      "relationships": {
        "role": {
          "data": {
            "id": "1",
            "type": "role"
          }
        }
      }
    },
    {
      "id": "12",
      "type": "accountabilities",
      "attributes": {
        "description": "immersive experience",
        "created_at": "2020-01-16T18:38:26.507Z",
        "updated_at": "2020-01-16T18:38:26.507Z"
      },
      "relationships": {
        "role": {
          "data": {
            "id": "1",
            "type": "role"
          }
        }
      }
    },
    {
      "id": "3",
      "type": "accountabilities",
      "attributes": {
        "description": "rubber meets the road",
        "created_at": "2020-01-16T18:38:26.466Z",
        "updated_at": "2020-01-16T18:38:26.466Z"
      },
      "relationships": {
        "role": {
          "data": {
            "id": "3",
            "type": "role"
          }
        }
      }
    }
  ]
}
```
How come the `type` value in `relationships` is still singular at this point? I think that is where I am stuck. 
Once again, thank you for looking into this. It has been bugging me for a few days now and I'm curious to see what I have missed.

**Comment by stas** [comment]
@BFranse could you add please the `record_type: :accountabilities` to the `has_many` in your serializers too.

There are some examples here:
https://github.com/fast-jsonapi/fast_jsonapi#customizable-options

We are aware of this issue and it's been described in #32

**Comment by BFranse** [comment]
> @BFranse could you add please the `record_type: :accountabilities` to the `has_many` in your serializers too.
> 
> There are some examples here:
> https://github.com/fast-jsonapi/fast_jsonapi#customizable-options
> 
> We are aware of this issue and it's been described in #32

@stas Thank you so much! Adding `record_type: :accountabilities` did the trick and changed the response. I must have missed that while going over the readme.
Thank you once again for your help and patience.
