### ISSUE TITLE
You're forked. Now what?

### ISSUE THREAD

**Issue by JeffLuckett** [fast-jsonapi/fast_jsonapi#56]
Just a question about the "go forward" plan.

The parent maintainers appear to have gone totally dark on their repo, are any of the maintainers here in contact with them?

Assuming that any back channel communications are as dead as the repo appears to be, is there any plan to become "official" and start publishing a perhaps differently named gem on RubyGems?

It makes it a harder sell to include this library in an Enterprise project pulling from GitHub rather than RubyGems.

I'm using this gem #in a side project (and am so-far very happy with it) with the hope of bringing this to my employer's project, but really need to know the "go forward" plan.  We _can_ use "unpublished" gems, but company policy is that we have to fill the repo into our corporate account which brings some level of additional maintenance overhead.  I'd much rather be able to pull from RubyGems, where we automatically mirror the gems we use in our own repo.

Thanks, and keep up the good work!

**Comment by stas** [comment]
@JeffLuckett thanks for reaching out!


> are any of the maintainers here in contact with them?

We are trying, not very successfully though. Honestly there's indeed quite a bit of uncertainty about how to proceed next. We're trying to _play nice_ with everyone, but lately I feel like we should rename the fork and push forward independently.

An alternative way is to use the Github's gem repository and keep the releases outside of RubyGems for a bit... Let's continue the conversation as part of the #1
