### ISSUE TITLE
Comparison with similar libraries

### ISSUE THREAD

**Issue by oyeanuj** [fast-jsonapi/fast_jsonapi#57]
Hey folks, y'all are doing a great job managing this fork, and making things happen, congrats!

I have a request similar to #38 - I'm curious if in the ReadMe or in the docs, there can be a section which provides a comparison to other similar libraries like ([jsonapi-rails](https://github.com/jsonapi-rb/jsonapi-rails), [Panko](https://github.com/yosiat/panko_serializer), [jsonapi-serializers](https://github.com/fotinakis/jsonapi-serializers), [jsonapi-resources](https://github.com/cerebris/jsonapi-resources), [blueprinter](https://github.com/procore/blueprinter)) to help people make an educated choice about the pros and cons. 

Thoughts?

**Comment by stas** [comment]
@oyeanuj there's a benchmark to compare across with alternatives:
https://github.com/fast-jsonapi/fast_jsonapi/blob/master/spec/lib/object_serializer_performance_spec.rb#L17-L34

Panko and Blueprinter are not covering the JSON:API spec. Does this answer the question?

**Comment by oyeanuj** [comment]
@stas thanks for the quick response! That’s helpful although I was originally looking for feature/behavior comparison. Thoughts on that?

**Comment by stas** [comment]
@oyeanuj what do you mean by feature comparison? The libraries from above represent the implementation of the https://jsonapi.org spec. This is not a generic serialization library.

**Comment by oyeanuj** [comment]
@stas I do understand that but I meant the difference outside of implementing the spec. Given 3 libraries implementing the spec, help users understand the tradeoffs and make an informed choice. For eg, I can imagine talking about how this library offers conditional relationships, deals with collections or params, etc and may be more fully featured for someone coming from AMS .

**Comment by stas** [comment]
@oyeanuj I'm not going to stop you from doing that sort of comparison, but generally speaking, I find it very subjective and out of scope of this project :)

A more complete list of JSON:API related libraries is also available at:
https://jsonapi.org/implementations/#server-libraries-ruby

I will close this issue, but feel free to send a PR with a third-party repository/website when you have something. We will review it and merge it if it provides value to the project documentation.

Thanks again for the suggestion.

**Comment by stas** [comment]
@oyeanuj as part of #69 there's now https://github.com/fast-jsonapi/comparisons

Feel free to send PRs there if you want to highlight some of the aspects...
