### ISSUE TITLE
Specifying attributes of nested/included objects

### ISSUE THREAD

**Issue by oyeanuj** [fast-jsonapi/fast_jsonapi#61]
Hi folks! I'm migrating from AMS 0.9x to this excellent library (thank you for maintaining this fork!). I have a lot of cases like the following:
```rb
  # Relationships that use only, include or except in some serializer

   has_one: :drink,
    only: [:name, :origin]

  has_one. :drinkable,
    polymorphic:  true,
    except: 	 [:price, :availability]
```

Since those keywords don't work, I'm wondering what is the best way to achieve a similar outcome with this library?

**Comment by stas** [comment]
@oyeanuj could you help us find the documentation for this exact functionality you're looking to replicate please?

I'm not familiar with AMS options. It seems like these are suggesting a very close integration with the ActiveRecord API, in which case there's no such alternative in `fast_jsonapi`.

Instead, you can leverage the [sparse fieldsets](https://github.com/fast-jsonapi/fast_jsonapi#sparse-fieldsets) and the [compound document](https://github.com/fast-jsonapi/fast_jsonapi#compound-document) options functionality.

**Comment by oyeanuj** [comment]
Absolutely, [here](https://github.com/rails-api/active_model_serializers/tree/0-9-stable#embedding-polymorphic-associations) and [here](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/serializers.md#polymorphic-relationships) is the polymorphic fields in the documentation. The `only`, `include`, and `except` options don't seem to be well-documented except in changelogs.

**Comment by stas** [comment]
@oyeanuj looks a bit obscure. I still find it a very ORM specific functionality and I don't think that's the scope of this project. If you want to add some optimizations, you can use sparse fields to prepare the query before you pass it over to the serializer though.

I'll be closing this for now.
