### ISSUE TITLE
Deep transform keys for complex attributes

### ISSUE THREAD

**Issue by attilahorvath** [fast-jsonapi/fast_jsonapi#62]
## Expected Behavior

Sometimes I'd like to use more complex attributes with arrays and structures, arbitrarily nested within each other. The JSON:API spec explicitly allows this:

> Complex data structures involving JSON objects and arrays are allowed as attribute values.

https://jsonapi.org/format/#document-resource-object-attributes

However, the keys of nested objects are not being translated right now.

## Actual Behavior

The nested attribute keys don't get translated into the specified format.

## Steps to Reproduce the Problem

For example:

```ruby
class MovieSerializer
  include FastJsonapi::ObjectSerializer

  set_key_transform :camel_lower

  attribute :statistics do
    {
      awards_won: 2,
      filming_duration: { filming_years: 2, filming_months: 6 },
      filming_locations: ['Toronto', 'Los Angeles']
    }
  end
end
```

I would expect the serialized JSON to contain all the nested keys in camel case as well but they don't get translated, only the top level ones.

## Specifications

  - Version: Latest unreleased `master`
  - Ruby version: 2.6.5p114

## More Details

I'm more than happy to work on this myself and submit a PR but I wanted to have a bit of discussion as to how to go about this first. This would potentially be a breaking change as there might be apps already depending on nested attributes not being translated so this could warrant a major version bump. Or, we could keep this behavior as the default and issue a new optional flag that triggers this deep transform of keys.

What are your thoughts about this?

**Comment by stas** [comment]
@attilahorvath thanks a lot for your PR and for bringing this up for discussion.

I think you do have a point, but I don't think it's a bug. Simply put, a more common use-case, where the attribute value is a Hash representing a JSON(b) document, suggests that the format of the value should not be altered.

I believe indeed can help here and provide a helper method to transform a nested document according to the selected case, but this should be an user-land concern, not a library one.

It would be nice to hear the opinion of the rest of the crew as well @fast-jsonapi/core and @christophersansone

**Comment by christophersansone** [comment]
FWIW, ActiveModel Serializers does indeed convert nested attributes, and the difference in behavior was one of the "gotchas" I faced when converting a large app from AMS to FJ.

I think it stands to reason that if you want your API to expose property names in a format other than Ruby's, you would want to do it throughout the entire JSON document, which includes nested data.  It doesn't really make sense to only transform one level deep.

That said, I think it makes sense for the library to offer this ability.  Of course, we still need to offer the existing behavior, and the existing behavior needs to be the default so that we avoid breaking changes.  I think we can offer an opt-in flag, maybe something like:

```
set_key_transform :camel_lower, nested: true
```

**Comment by attilahorvath** [comment]
Okay, I'll try to submit a PR using this proposed syntax then and we can discuss this feature further once that's ready.

I think there could be a global config variable for this as well to avoid having to specify this flag each time. Something like:

```ruby
# config/initializers/fast_jsonapi.rb

FastJsonapi.transform_nested_keys = true
```

That would also make it easier to make this the default behavior in the future eventually in a possible next major version, we'd just have to flip the default value of this flag.

**Comment by christophersansone** [comment]
@attilahorvath Thanks!  Agreed that some sort of global configuration for features like key transformation would be helpful.  I personally always have a base serializer class with all of my configurations specified, and then I simply inherit from that class for all of my serializers.

**Comment by stas** [comment]
@attilahorvath @christophersansone I still don't think this is the right direction and the presented arguments are not convincing. We can provide an API method that will help developers deeply transform their serializable objects into the same type, but that should be their decision and their implementation. 

Long story short, I don't want this library to be responsible for messing up with non-JSON:API specific data of the user. This functionality is not covered by the spec, so we're free to veto it.

**Comment by kpheasey** [comment]
I'm going to second @stas. The nested objects are not bound by the json api specification.  The specification only says that they can exist.  Therefore, this gem can not apply transformations to those objects.

I personally have some 'dirty' objects in some of my api's that use a different naming scheme for keys.  Specifically, it creates configuration objects for highchart.js.

**Comment by christophersansone** [comment]
@stas @kpheasey I'm having a bit of trouble with the reasoning that we cannot apply transformations to nested data because it is "not bound by the JSON:API spec".  The spec makes no mention of how top-level attribute and relationship names are specified either, and yet this library offers it.  I just don't see why the line in the sand is that it should only transform one level deep.

If an API designer wants their keys camel cased, it stands to reason that they would often want ALL of their keys camel cased, including nested data.  I think it would typically be very strange to look at a JSON:API output and see some keys camel cased and other keys underscored just because some of the data was nested.

@kpheasey I understand your use case.  That's why it should be optional.

Are there any other suggestions to support this use case?  Or is the decision to that it is solely up to the developer to build their own conversion?

**Comment by kpheasey** [comment]
If you want the serializer to transform the keys, there are currently two ways:
1. Create a serializer to represent the complex object. (see complex attribute below).
2. Apply the transformation yourself with an attribute block. (see complex_alt attribute below).

```ruby
class JobSerializer
  include FastJsonapi::ObjectSerializer

  attributes :id
  attribute :complex do |obj|
    ComplexSerializer.new(obj.complex).serializable_hash
  end

  attribute :complex_alt do |obj|
    obj.deep_transform_keys { |key| key.camelize(:lower) }
  end
end
```

Unless every api object is made up of multiple complex objects as attributes, this isn't much overhead.  I only see overhead when porting from another gem like AMS.

**Comment by stas** [comment]
> @kpheasey Thanks for offering your use case, that's helpful. In my opinion, this is an example of why it should be optional, rather than concluding that it should never be supported.
> 
> Are there any other suggestions to support this use case? Or is the decision to that it is solely up to the developer to build their own conversion?

I see no reason we should provide this as a feature. It looks very straightforward based on @kpheasey examples. Let's focus on the stuff that we really need to take care of.

Thanks to all for sharing their feedback and ideas. @attilahorvath feel free to add an article in the `docs`, I'll be happy to merge it.

**Comment by attilahorvath** [comment]
@stas I was just in the middle of composing a response when you closed it, hope you don't mind me sharing one last example to explain why I'd really like this feature. :sweat_smile: 

I have financial transactions stored in the DB for each user with different currencies and I want to show a sum per currency. I'm doing something like this:

```ruby
# app/models/user.rb

def transactions_by_currency
  transactions.group(:currency).sum(:amount).map do |currency, amount|
    {
      currency_code: currency,
      sum_amount: sum
    }
  end
end
```

Now, if we had this feature, the serializer could be as simple as:

```ruby
# app/serializers/user_serializer.rb

class UserSerializer < ApplicationSerializer
  attribute :transactions_by_currency
end
```

However, right now I have to do basically:

```ruby
# app/serializers/user_serializer.rb

class UserSerializer < ApplicationSerializer
  attribute :transactions_by_currency do |user|
    user.transactions_by_currency.map do |item|
      item.transform_keys do |key|
        key.to_s.camelize(:lower)
      end
    end
  end
end
```

I shouldn't use a `has_many` here because these sums are not separate resources. I can't even use a different serializer for them as suggested because there is no good candidate for `id` and `type` - both of which must be present otherwise I get an error. So I'm out of nicer options here.

---

The JSON:API spec says this on naming:

> Member names SHOULD be camel-cased (i.e., wordWordWord)

https://jsonapi.org/recommendations/#naming

This is just a `SHOULD` recommendation so it's not a good argument either for or against this feature - or even for translating the top level keys for that matter which is already being done by this gem. So I'm not sure why it's been brought up here.

Honestly, this all feels more like an oversight by the original authors of this gem - there are no examples or tests covering the usage of nested attributes so they probably haven't really considered this use case. Other similar gems all do deep key translations as far as I can tell - see e.g. AMS or OliveBranch.

---

Thanks for all the work you've put into maintaining this gem since the original authors have apparently abandoned it unfortunately. I understand if you don't want to include more features than you deem necessary, I just wanted to explain why it's a sticking point for me.

**Comment by stas** [comment]
@attilahorvath I'm not sure I follow, aside from the two examples that Kevin shared, the [attributes API allows a proc being passed](https://github.com/fast-jsonapi/fast_jsonapi#attributes) which can basically be the serializer method:
```ruby
class UserSerializer < ApplicationSerializer
  attribute :transactions_by_currency, &:pretty_transactions_by_currency

  private
  def pretty_transactions_by_currency(user)
    # Your own way to deal with nested data...
    user.transactions_by_currency.deep_transform_keys { |key| key.camelize(:lower) }
  end
end
```

So if it's a matter of _sugar_, this can't get more cleaner and explicit.



> The JSON:API spec says this on naming:
> 
> > Member names SHOULD be camel-cased (i.e., wordWordWord)
> 
> https://jsonapi.org/recommendations/#naming
> 
> This is just a `SHOULD` recommendation so it's not a good argument either for or against this feature - or even for translating the top level keys for that matter which is already being done by this gem. So I'm not sure why it's been brought up here.
> 
> Honestly, this all feels more like an oversight by the original authors of this gem - there are no examples or tests covering the usage of nested attributes so they probably haven't really considered this use case. Other similar gems all do deep key translations as far as I can tell - see e.g. AMS or OliveBranch.

The recommendations page is up to everyone's interpretation. It's not an oversight, the spec covers vital aspects of an API design, not every possible use-case in the world. Things that are not vital (like this one), are not worth being covered/enforced.

> Thanks for all the work you've put into maintaining this gem since the original authors have apparently abandoned it unfortunately. I understand if you don't want to include more features than you deem necessary, I just wanted to explain why it's a sticking point for me.

Attila, I don't mind introducing features, but this is an extremely subjective request that can cause unexpected outcomes which, both, me and Kevin pointed out and none of the answers provided here were covering our concerns.

I appreciate the enthusiasm, and I'm leaving this conversation open, but I think we're good so far with the support for this particular question. :bowing_man:

**Comment by christophersansone** [comment]
> ... this is an extremely subjective request that can cause **unexpected** outcomes ...

Woo hoo, I think we are all in agreement on this part! 💯:smile:  When someone has specified a key transform, the expectation of nested output is very unclear.  @attilahorvath and I would expect it to transform nested keys as well, and @stas and @kpheasey would not.

At least some other libraries (I know AMS in particular) fall on the other side of the debate and will transform nested keys, so I have to believe that it's a reasonably popular opinion to want nested data to be transformed.  And not supporting it may be a blocker for someone migrating a project from another library like AMS.

Regardless of which side anyone is on, could we agree that the library's current API / DSL is unclear in this regard?  And by improving the API, we can bring greater clarity to the expected behavior?

> ... none of the answers provided here were covering our concerns.

Would you mind clarifying what your concerns are?  If we implement something in the DSL that will offer greater clarity either way (e.g. `set_key_transform :camel_lower, nested: true`), and require the developer to opt into the nested behavior, what additional concerns would you have?

**Comment by kpheasey** [comment]
@christophersansone If you would like to extend the functionality via a module that can be placed in the equivalent of `/config/initializers`, we can add that to a wiki page and link from the docs.

Here's an example of one for pluralizing association names -> https://gist.github.com/kpheasey/8ad17668ae9194bfd276a5e8f70eff03

**Comment by dmolesUC** [comment]
> If you want the serializer to transform the keys, there are currently two ways:
> 
> 1. Create a serializer to represent the complex object. (see complex attribute below).

@kpheasey Assuming the serializer includes `FastJsonapi::ObjectSerializer`, I think this only works if the complex object has an `id`; if it doesn't, you get

```none
FastJsonapi::MandatoryField:
  id is a mandatory field in the jsonapi spec
# /usr/local/bundle/gems/jsonapi-serializer-2.2.0/lib/fast_jsonapi/serialization_core.rb:124:in `id_from_record'
```

You can work around this with some overrides —

```ruby
class << self
  def id_hash(*_args)
    {}
  end

  def id_from_record(*_args)
    nil
  end
end
```

— but it's a pain.

(Side note: besides making `id` optional, being able to specify `serializer:` on attributes as well as relationships would make this kind of non-Rails-y complex-object use case cleaner.)

**Comment by kpheasey** [comment]
@dmolesUC, According to the JSON:API spec, the id is required, unless it's a new object originating from the client and doesn't have an id yet.

https://jsonapi.org/format/1.1/#document-resource-object-identification

Can you speak more about the `serializer:` request?  I'm unsure of a use case where an attribute would represent an object that is not a relationship?
