### ISSUE TITLE
Do not return empty "relationships" object

### ISSUE THREAD

**Issue by sirdharma** [fast-jsonapi/fast_jsonapi#73]
Hi 👋

## Expected Behavior

The "relationships" object shouldn't be present.

## Actual Behavior

The "relationships" object is present and is empty: `"relationships": {}`

## Steps to Reproduce the Problem

  1. Create a serializer with only one conditional relationship. Any object that fails the condition on the relationship will be serialized with `"relationships": {}`. 

JSON:API [requires](https://jsonapi.org/format/#document-resource-object-relationships) that:
> The value of the relationships key MUST be an object (a “relationships object”). Members of the relationships object (“relationships”) represent references from the resource object in which it’s defined to other resource objects.

It is not very clear (at least to me) if returning an empty "relationships" object is allowed.

## Specifications

  - Version: 1.6.0
  - Ruby version: 2.6.5

Thanks!

**Comment by stas** [comment]
Thanks @sirdharma 

The spec states clearly that the _relationship object_ should be present and include at least on of `links`, `data` and `meta`. Where `data` can actually be `null`:
https://jsonapi.org/format/#document-resource-object-linkage

I'll be closing this, but let me know if you have other questions.

**Comment by stas** [comment]
:bowing_man: 

It might be that we're not including always the `"relationship": { "data": null }` on empty relationships though. If that's an issue for you, we can open a separate issue and try to prioritize it.

**Comment by sirdharma** [comment]
All good for now thanks! I'll open a PR if need be.

👍
