### ISSUE TITLE
Relationships with params

### ISSUE THREAD

**Issue by kln** [fast-jsonapi/fast_jsonapi#83]
I had a serializer with conditional attributes

```ruby
class UserSerializer
  include FastJsonapi::ObjectSerializer

  attribute :phone do |object, params|
    params[:hide_contact] == true ? '' :  object.phone
  end
end
```

But can't use this serializer as a relationship

## Expected Behavior

```
  belongs_to :candidate, serializer: CandidateSerializer, params: { hide_contact: true }
```

## Actual Behavior
`params`or `options` are ignored

Can I do it somehow?

**Comment by stas** [comment]
@kln please review the API for conditional attributes/relationships:
https://github.com/fast-jsonapi/fast_jsonapi#conditional-attributes

Let me know why that doesn't work for you...

Thanks

**Comment by kln** [comment]
> @kln please review the API for conditional attributes/relationships:
> https://github.com/fast-jsonapi/fast_jsonapi#conditional-attributes
> 
> Let me know why that doesn't work for you...
> 
> Thanks

Thanks, @stas 

I don't understand why, are two serializers like

```
# first

class UserSerializer
  include FastJsonapi::ObjectSerializer

  attribute :phone do |object, params|
    params[:hide_contact] == true ? '' :  object.phone
  end
end

# second

class AnotherSerializer
  include FastJsonapi::ObjectSerializer

  belongs_to :user, serializer: UserSerializer, params: { hide_contact: true }
end
```

If I call `UserSerializer` with `params` it works, but on the relationship isn't. 

I would like to know if I can do it

**Comment by kln** [comment]
I added the parameter at first serializer `AnotherSerializer` and used it into UserSerializer

**Comment by stas** [comment]
@kln is this still an issue for you?

**Comment by TheTharin** [comment]
@kln Can you give an example of how you managed to solve the problem? How did you pass the parameter from first serializer into the relationship serializer?
