### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by stas** [fast-jsonapi/fast_jsonapi#86]
Since it's clear that we have to move forward with this project without any further assistance from the original authors, [we need to pick a new name](https://github.com/fast-jsonapi/fast_jsonapi/issues/81#issuecomment-630228783) for this project.

Please leave a comment with the name you think reflects better the scope and purpose of this gem. It is important to note that:
 * the rubygems.org name should be available
 * the name should be different from the original name

The comments with the most votes (:heart:) will be considered the main candidates.
Thank you all :upside_down_face:

**Comment by jits** [comment]
Couple of questions to help with this naming exercise:

1. Is there an intention for this fork to cater for more formats than JSON:API in the future?
1. Will this fork continue the "performance first" approach mentioned by the README and https://github.com/fast-jsonapi/fast_jsonapi/blob/master/docs/performance_methodology.md?
1. What level of backwards compatibility will this fork intend to have?

Also, will the license be kept the same? (Apache 2.0)

**Comment by stas** [comment]
I think we have no reasons to change the license, so that stays.

1. This is a great question, and honestly I'm inclining towards leaving it as a pure library with one purpose and not moving into covering the full spec, something that I did with the [jsonapi.rb](https://github.com/stas/jsonapi.rb) (error handling, filters, pagination and so on...).
2. I can see how this could be relevant, but I don't think the name should reflect it. I do believe that we obviously should keep the _performance engineering spirit_  present, but if somebody smarter decides to do a similar implementation and it's faster, that's just fine.
3. We could provide a light backwards compatibility layer, but to be honest, folks who are using this library will already have to update gemspec/require refs, so I don't think we need major changes. Though some specific API methods will change signatures since #34  and #45 are just very :exploding_head: ...

**Comment by jits** [comment]
Thanks @stas for the quick and informative response! All makes sense to me and I very much agree. Sounds like the goal is to keep things simple and cohesive, but also have the freedom to change and improve the existing implementation.

Will think of some names, and I hope to contribute / help out with PRs etc. in the future.

**Comment by kpheasey** [comment]
FastJson / fast_json

**Comment by jits** [comment]
`jsonapi_printer`

**Comment by jits** [comment]
`jsonapi_presenter`

**Comment by jits** [comment]
`jsonapi_transformer` OR `transform_to_jsonapi`

I like this theme as it fits with the way the library works – it doesn't assume serialisation, and you can do what you want with the "transformed" object.

**Comment by stas** [comment]
`jsonapi-serializer`

**Comment by kimyu92** [comment]
`lightning-jsonapi`

**Comment by Zungong** [comment]
`quick_jsonapi`

**Comment by killernova** [comment]
flash-jsonapi

**Comment by DVG** [comment]
Following in the footsteps of can_can -> can_can_can I humbly suggest `fast_fast_jsonapi`. I'd prefer keeping the original name in the project name for discoverability, and would suggest that getting something pushed to rubygems for ease of installation sooner rather than later would be ideal.

**Comment by DVG** [comment]
Or community_fast_jsonapi ¯\_(ツ)_/¯

**Comment by kimyu92** [comment]
> Following in the footsteps of can_can -> can_can_can I humbly suggest `fast_fast_jsonapi`

Inspired from this comment, `super_fast_jsonapi`

**Comment by stas** [comment]
> Following in the footsteps of can_can -> can_can_can I humbly suggest `fast_fast_jsonapi`. I'd prefer keeping the original name in the project name for discoverability, and would suggest that getting something pushed to rubygems for ease of installation sooner rather than later would be ideal.

@DVG @kimyu92  thanks, but please let's keep it on-topic. If you don't think we've provided clear arguments on why this name should follow the rules we set, please ask away, I'll be happy to explain. 

Both your suggestions will be ignored. Sorry.

**Comment by DVG** [comment]
You are welcome to ignore whatever you choose to, I'm just some guy.

**Comment by chrisgeek** [comment]
Since it is expected to be fast, sleek and lightweight, I would suggest `smart_jsonapi`

**Comment by gee-forr** [comment]
Is anyone opposed to `fast_jsonapi_serializer`? It hits these notes:

- Name is available
- Does what it says on the tin
- Close enough to the original project's name to signal it's related.

I wouldn't mind taking a crack at renaming it if you all like this name? Let me know.

**Comment by stas** [comment]
> Is anyone opposed to `fast_jsonapi_serializer`? It hits these notes:

@gee-forr `jsonapi-serializer` is shorter and has a bunch of votes. We'll proceed with that. Thanks to everyone for helping with this! <3

**Comment by stas** [comment]
```
  Successfully built RubyGem
  Name: jsonapi-serializer
  Version: 2.0.0
  File: jsonapi-serializer-2.0.0.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: jsonapi-serializer (2.0.0)
```
It's out! :partying_face: 

https://rubygems.org/gems/jsonapi-serializer
