### ISSUE TITLE
Version is not the same with the release

### ISSUE THREAD

**Issue by faqndo97** [fast-jsonapi/fast_jsonapi#93]
## Expected Behavior

Be able to install the gem in the way explained in the RADME.md, that is adding this in Gemfile:

`gem 'fast_jsonapi', '~> 1.7.2', git: 'https://github.com/fast-jsonapi/fast_jsonapi'`

## Actual Behavior

```
Fetching https://github.com/fast-jsonapi/fast_jsonapi
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'fast_jsonapi (~> 1.7.2)' in https://github.com/fast-jsonapi/fast_jsonapi (at master@3ff69cc).
The source contains 'fast_jsonapi' at: 2.0.0
```

## Steps to Reproduce the Problem

  1. create new rails project
  2. put `gem 'fast_jsonapi', '~> 1.7.2', git: 'https://github.com/fast-jsonapi/fast_jsonapi'` on Gemfile
  3. run `bundle install`

## Specifications

  - Rails Version: 6.0.3
  - Ruby version: 2.7.0

After a small research, in the last [commit](https://github.com/fast-jsonapi/fast_jsonapi/commit/3ff69ccce1a75fb0210874dba1b77f05a79ec8f2) on master, the version was changes but not a new release was created.

**Comment by faqndo97** [comment]
Just to add a comment, I fixed the problem not specifying the version on Gemfile, but the new release should be created or the readme should be updated I think

**Comment by stas** [comment]
Thanks @faqndo97!

I'll close this, since we're just late with #86 which should fix everything related to releases :see_no_evil: :bow:
